amcl:
  ros__parameters:
    use_sim_time: true                     # 시뮬레이션 시간 사용
    laser_scan_topic: scan                # 2D LaserScan 토픽 (3D → scan 변환 필요)
    odom_topic: odom                       # EKF/SLAM 기반 odom 토픽
    map_topic: "/map"  # octomap_server2가 퍼블리시하는 맵  
    base_frame_id: base_link            # 로봇의 기본 프레임 (base_link)
    odom_frame_id: odom
    global_frame_id: map

    # 모션 모델 오차 계수 (IMU + odom 사용, 안정적인 보행기 기반)
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2

    # 관측 모델 설정 (likelihood_field recommended)
    laser_model_type: "likelihood_field"
    laser_z_hit: 0.5
    laser_z_rand: 0.5
    laser_sigma_hit: 0.2

    laser_likelihood_max_dist: 2.0
    laser_max_range: 30.0
    laser_min_range: 0.1
    max_beams: 60

    # 파티클 수 설정 (대회 환경에서 빠르고 다양한 디버깅 가능하게)
    min_particles: 500
    max_particles: 2000
    resample_interval: 2

    # 초기 위치 획득 + 재위치(pose update) 간격
    transform_tolerance: 0.5
    save_pose_rate: 1.0

    # beam skip 기능 (빠르게 지나가는 사람/작은 장애물 무시)
    do_beamskip: true
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9

    # recovery 관련
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: true

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: true
