behavior_server:
  ros__parameters:
    use_sim_time: true                              # 시뮬레이터 시간 사용 (필요 시 true)

    cycle_frequency: 10.0                           # 행동 실행 주기 (Hz)

    # 로컬/글로벌 costmap과 로봇 외형 정보 topic
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint

    # frame 설정
    local_frame: odom                               # 로컬 행동 기준 프레임 (odom)
    global_frame: map                               # 글로벌 행동 기준 프레임 (map)
    robot_base_frame: base_link                     # 로봇 기준 프레임

    transform_timeout: 0.1                          # TF 조회 timeout (초)
    simulate_ahead_time: 2.0                        # 행동 시뮬레이션 시간
    max_rotational_vel: 1.0                         # 최대 회전 속도
    min_rotational_vel: 0.4                         # 최소 회전 속도
    rotational_acc_lim: 3.2                         # 회전 가속도 제한

    enable_stamped_cmd_vel: true                    # geometry_msgs/msg/TwistStamped 타입 사용 여부
  
    # 사용할 행동 플러그인 목록
    behavior_plugins:
      - spin
      - backup
      - drive_on_heading
      - wait
      - assisted_teleop

    # 개별 행동 정의
    spin:
      plugin: "nav2_behaviors/Spin"                # 제자리 회전
    backup:
      plugin: "nav2_behaviors/BackUp"              # 후진
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"      # 특정 방향으로 직진
    wait:
      plugin: "nav2_behaviors/Wait"                # 지정 시간 대기
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"      # 수동 조작 중 장애물 자동 회피
