bt_navigator:
  ros__parameters:
    use_sim_time: true

    global_bt_xml_filename: "bt_tree.xml"
    default_server_timeout: 20
    default_nav_through_poses_bt_xml: "navigate_through_poses_w_replanning.xml"
    default_nav_to_pose_bt_xml: "bt_tree.xml"

    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node     # ✅ 추가
      - nav2_is_path_valid_condition_bt_node
      - nav2_wait_for_path_bt_node

    # 🔽 선택자 작동 시 반드시 필요
    default_planner: "SmacPlannerHybrid"
    default_controller: "DWBLocalPlanner"
    default_goal_checker: "general_goal_checker"

    # ✅ 선택 플러그인 명시
    planner_selector: "selected_planner"
    controller_selector: "selected_controller"
    goal_checker_selector: "selected_goal_checker"

    # ✅ goal checker selector 설정
    goal_checker_plugins:
      general_goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.25
        yaw_goal_tolerance: 0.25
        stateful: true

      precise_goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.05
        yaw_goal_tolerance: 0.05
        stateful: true

    progress_checker_plugin: "nav2_controller::SimpleProgressChecker"
    progress_checker_plugins:
      nav2_controller::SimpleProgressChecker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0

    recovery_enabled: true
    number_of_retries: 6
    recovery_plugins:
      spin: "nav2_recoveries/Spin"
      back_up: "nav2_recoveries/BackUp"
      wait: "nav2_recoveries/Wait"
      clear_costmap_global: "nav2_recoveries/ClearCostmap"
      clear_costmap_local: "nav2_recoveries/ClearCostmap"

    spin:
      plugin: "nav2_recoveries/Spin"
      spin_dist: 1.57
      time_allowance: 5.0
      max_rotational_vel: 1.0
      min_rotational_vel: 0.4
      rotational_acc_lim: 3.2

    back_up:
      plugin: "nav2_recoveries/BackUp"
      backup_dist: 0.3
      backup_speed: 0.15

    wait:
      plugin: "nav2_recoveries/Wait"
      wait_duration: 5

    clear_costmap_global:
      plugin: "nav2_recoveries/ClearCostmap"
      costmap_name: global_costmap
      reset_distance: 3.0

    clear_costmap_local:
      plugin: "nav2_recoveries/ClearCostmap"
      costmap_name: local_costmap
      reset_distance: 3.0
