controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0

    # 최소 속도 threshold
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    # 컨트롤 실패 허용 오차
    failure_tolerance: 0.3

    # 컨트롤러 플러그인 목록
    controller_plugins:
      - RegulatedPurePursuitController
      - DWBLocalPlanner

    # Goal Checker 플러그인 목록
    goal_checker_plugins:
      - general_goal_checker
      - precise_goal_checker

    # Goal Checker 설정
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    precise_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: true
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05

    # Regulated Pure Pursuit Controller 설정
    RegulatedPurePursuitController:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      goal_checker_id: "general_goal_checker"

      desired_linear_vel: 0.6
      min_linear_vel: 0.1
      max_linear_vel: 0.8
      lookahead_dist: 0.6
      use_velocity_scaled_lookahead_dist: true
      min_lookahead_dist: 0.4
      max_lookahead_dist: 1.0

      rotational_vel_limit: 1.5
      lookahead_time: 1.5
      transform_tolerance: 0.3   # 0.5 → 0.3 권장 (frame lookup delay 방지)

      use_regulated_lookahead: true
      use_cost_regulated_scaling: true
      cost_scaling_dist: 0.6
      cost_scaling_gain: 3.0
      inflation_cost_scaling_factor: 0.5

      use_dynamic_constraints: true
      max_allowed_time_to_collision_up_to_carrot: 1.5
      use_collision_checker: true
      linear_vel_scaling_factor: 0.8
      angular_vel_scaling_factor: 1.2

    # DWB Local Planner 설정
    DWBLocalPlanner:
      plugin: "dwb_core::DWBLocalPlanner"
      goal_checker_id: "general_goal_checker"

      min_vel_x: 0.0
      max_vel_x: 0.8
      min_vel_y: 0.0
      max_vel_y: 0.2
      min_speed_xy: 0.0
      max_speed_xy: 0.8
      min_speed_theta: 0.0
      max_vel_theta: 1.5

      acc_lim_x: 1.5
      acc_lim_y: 1.0
      acc_lim_theta: 2.0
      decel_lim_theta: -2.0

      vx_samples: 20
      vy_samples: 10
      vtheta_samples: 40
      sim_time: 2.0

      linear_granularity: 0.05
      angular_granularity: 0.025
      time_granularity: 0.025

      xy_goal_tolerance: 0.25
      trans_stopped_vel: 0.05
      theta_stopped_vel: 0.05

      critics:
        - RotateToGoal
        - PathAlign
        - GoalAlign
        - BaseObstacle
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      BaseObstacle.scale: 0.05
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: 1.0
