global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 2.0
    publish_frequency: 1.0
    transform_tolerance: 0.5
    track_unknown_space: true

    rolling_window: false
    width: 20.0
    height: 20.0
    resolution: 0.05

    # footprint는 한 줄로 표현하거나 |+ 블럭 형식을 써야 오류 없음
    footprint: "[[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]"

    plugins:
      - static_layer
      - obstacle_layer
      - inflation_layer

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true
      subscribe_to_updates: false

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        sensor_frame: velodyne_link
        data_type: LaserScan
        clearing: true
        marking: true
        obstacle_range: 2.5
        raytrace_range: 3.0
      max_obstacle_height: 0.6

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.4
      cost_scaling_factor: 2.5
