goal_checker_selector:
  ros__parameters:
    use_sim_time: true

    goal_checker_plugins: ["general_goal_checker", "precise_goal_checker"]

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: True
      xy_goal_tolerance: 0.25                  # 일반적인 허용 오차
      yaw_goal_tolerance: 0.25

    precise_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: True
      xy_goal_tolerance: 0.05                  # 좁은 구간용 정밀 도달
      yaw_goal_tolerance: 0.05
