local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 5.0
    transform_tolerance: 0.3

    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05

    footprint: "[[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]"

    plugins:
      - obstacle_layer
      - voxel_layer
      - inflation_layer

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        sensor_frame: velodyne_link
        data_type: LaserScan
        clearing: true
        marking: true
        obstacle_range: 2.5
        raytrace_range: 3.0
      max_obstacle_height: 0.6

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: true
      origin_z: 0.0
      z_resolution: 0.05
      z_voxels: 16
      max_obstacle_height: 0.6
      mark_threshold: 0
      publish_voxel_map: false
      observation_sources: scan
      scan:
        topic: /scan
        sensor_frame: velodyne_link
        data_type: LaserScan
        clearing: true
        marking: true
        obstacle_range: 2.5
        raytrace_range: 3.0

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.4
      cost_scaling_factor: 2.5
