map_server:
  ros__parameters:
    use_sim_time: true               # 시뮬레이션 시간 사용 여부 (true면 /clock 사용, 시뮬 환경 필수)

    yaml_filename: "/path/to/map.yaml"  
    # 사용할 정적 맵 정보가 들어 있는 YAML 파일의 경로 (.pgm + .yaml 쌍)
    # LIO-SAM으로 SLAM 완료 후 저장한 맵 파일 지정

    topic_name: "map"               
    # 퍼블리시할 토픽 이름 (기본값: "map")
    # 다른 노드에서 /map 구독하여 사용함 (예: AMCL, costmap 등)

    frame_id: "map"                 
    # map 토픽의 좌표계 ID
    # 일반적으로 "map" 프레임 사용

    always_send_full_map: true      
    # true면 전체 맵을 주기적으로 다시 퍼블리시
    # false면 변경된 영역만 퍼블리시 (맵이 큰 경우 효율적이나, 복잡도 있음)

    publish_frequency: 1.0          
    # 전체 맵 퍼블리시 주기 (Hz)
    # 실시간 변경되지 않는 정적 맵이라면 0.5~1.0 적당

    # 아래 두 항목은 잘 사용되지 않지만, 고급 사용자용 설정임
    use_transient_local: true       
    # late-joining 노드가 마지막 퍼블리시된 맵을 받을 수 있도록 설정