planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 1.0

    planner_plugins:
      - SmacPlannerHybrid

    SmacPlannerHybrid:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"

      tolerance: 0.25
      downsample_costmap: true
      downsample_obstacle_layer: true

      allow_unknown: true
      max_iterations: 10000
      max_on_approach_iterations: 500
      max_planning_time: 2.0

      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 0.3
      reverse_penalty: 1.0
      change_penalty: 0.1
      non_straight_penalty: 0.123456789
      cost_penalty: 1.3
      rotation_penalty: 0.0
      analytic_expansion_max_length: 3.0
      analytic_expansion_max_cost: 400.0

      lookup_table_size: 20.0
      cache_obstacle_heuristic: true
      allow_reverse_expansion: true

      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
