recoveries_server:
  ros__parameters:
    use_sim_time: true                            # 시뮬레이터 시간 사용 여부 (필요시 true)

    cycle_frequency: 10.0                         # recovery behavior 실행 주기 (Hz)

    costmap_topic: local_costmap/costmap_raw      # 회피 시 사용하는 local costmap 데이터
    footprint_topic: local_costmap/published_footprint  # 로봇의 외형 정보 topic

    transform_timeout: 0.1                        # TF 조회 timeout (초)
    simulate_ahead_time: 2.0                      # 행동 시뮬레이션 시간 (예: 회전 동작 예측)
    max_rotational_vel: 1.0                       # 최대 회전 속도 (rad/s)
    min_rotational_vel: 0.4                       # 최소 회전 속도 (rad/s)
    rotational_acc_lim: 3.2                       # 회전 가속도 한계 (rad/s²)

    global_frame: odom                            # recovery 기준 전역 프레임 (보통 odom)
    robot_base_frame: base_link                   # 로봇 기준 프레임

    recovery_plugins:                             # 등록할 Recovery Behavior 목록
      - spin
      - backup
      - wait

    spin:
      plugin: "nav2_recoveries/Spin"              # 제자리 회전 (장애물 회피 목적)

    backup:
      plugin: "nav2_recoveries/BackUp"            # 후진 동작 (경로 막힘 등 상황)

    wait:
      plugin: "nav2_recoveries/Wait"              # 잠시 대기 (동적 장애물 회피 등 상황)

    # ➕ 향후 확장 가능한 custom recovery plugin 예시 (추가 시 사용)
    # climb_step:
    #   plugin: "custom_recoveries/StepClimb"     # 예: 계단 구간에서 자동 점프/단차 대응용
