smoother_server:
  ros__parameters:
    use_sim_time: true

    smoother_plugins: ["SavitzkyGolaySmoother"]

    SavitzkyGolaySmoother:
      plugin: "nav2_smoother::SavitzkyGolaySmoother"

      # 윈도우 크기와 다항 차수 (곡률 보정 수준)
      window_size: 11            # 홀수만 가능 (예: 5, 7, 9, 11)
      polynomial_order: 3        # 곡선 추종 정밀도. 2~4 권장

      # 간격 단위 설정
      apply_filter_twice: false  # 이중 보정 여부
      interpolate: true          # 중간 포인트 보간
      pad: true                  # 경계 영역 보존
      extend_path: false         # 경로 끝단 확장

      # 고급 설정 (기본값 권장)
      max_points: 2000
      tolerance: 1.0e-6
      debug_smoothing: false
