  velocity_smoother:
    ros__parameters:
      use_sim_time: true
      smoothing_frequency: 20.0  # cmd_vel 필터링 주기

      scale_velocities: false
      feedback: "CLOSED_LOOP"  # 로봇 피드백 활성화

      max_velocity:
        linear:
          x: 0.8
          y: 0.2
        angular: 1.5

      min_velocity:
        linear:
          x: 0.0
          y: 0.0
        angular: 0.0

      max_accel:
        linear:
          x: 1.0
          y: 0.5
        angular: 2.0

      max_decel:
        linear:
          x: -1.0
          y: -0.5
        angular: -2.0

      robot_feedback: false
