/ekf_local:
  ros__parameters:
    publish_tf: true
    frequency: 100.0
    sensor_timeout: 0.1
    two_d_mode: false   # 지상 2D면 true로 바꿔도 됨

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ===== IMU =====
    imu0: /imu/data
    # [x y z, roll pitch yaw, vx vy vz, vroll vpitch vyaw, ax ay az]
    imu0_config: [false, false, false,
                  true,  true,  false,
                  false, false, false,
                  true,  true,  true,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 50
    imu0_nodelay: true

    # ===== (선택) LIO-SAM 증분 오돔 같이 쓰고 싶으면 주석 해제 =====
    # odom0: /lio_sam/mapping/odometryIncremental
    # odom0_config: [true, true, true,
    #                true, true, true,
    #                true, true, true,
    #                true, true, true,
    #                false, false, false]
    # odom0_relative: true
    # odom0_differential: false
    # odom0_queue_size: 20
    # odom0_nodelay: true
